//! Generates `dnsmasq.conf` from the registry's domain suffix.
//!
//! Format reference: `man 8 dnsmasq` and the `address=` directive.
//! `address=/.<suffix>/127.0.0.1` makes dnsmasq answer with
//! `127.0.0.1` for any A query whose name ends in `.<suffix>` —
//! e.g. `address=/.test/127.0.0.1` matches `myapp.test`,
//! `api.myapp.test`, and so on.
//!
//! macOS only routes queries for the specific suffix to this dnsmasq
//! instance, via a small file in `/etc/resolver/<suffix>` written by a
//! separate command (the resolver-file install flow is its own card).
//! Until that file exists, dnsmasq runs but no resolutions actually
//! flow through it.

use std::path::PathBuf;

/// Build the dnsmasq config string. `port` is the UDP port the daemon
/// listens on locally — must be the same port `/etc/resolver/<suffix>`
/// will eventually reference.
pub fn build_config(suffix: &str, port: u16) -> String {
    // `bind-interfaces` + `listen-address=127.0.0.1` keeps dnsmasq off
    // any non-loopback interface. `no-daemon` keeps the process in the
    // foreground so Tauri's child-process supervisor sees it cleanly.
    // `no-resolv` + `no-hosts` keep the daemon from inheriting the
    // system resolver chain (we only want it to answer for our suffix).
    // `domain-needed` + `bogus-priv` are belt-and-suspenders to
    // suppress accidental forwarding of unqualified or RFC1918-reverse
    // queries to upstream nameservers.
    format!(
        "# Generated by PortBay — do not edit by hand.\n\
         # Regenerated whenever the registry's domain_suffix changes.\n\
         port={port}\n\
         no-daemon\n\
         no-resolv\n\
         no-hosts\n\
         domain-needed\n\
         bogus-priv\n\
         listen-address=127.0.0.1\n\
         bind-interfaces\n\
         address=/.{suffix}/127.0.0.1\n",
    )
}

/// Default location for the generated config. `<data_dir>/PortBay/dnsmasq.conf`.
pub fn default_config_path() -> std::io::Result<PathBuf> {
    let mut dir = dirs::data_dir()
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no data dir"))?;
    dir.push("PortBay");
    std::fs::create_dir_all(&dir)?;
    Ok(dir.join("dnsmasq.conf"))
}

/// Write the config to the default path; return where it landed.
pub fn write_config(suffix: &str, port: u16) -> std::io::Result<PathBuf> {
    let path = default_config_path()?;
    std::fs::write(&path, build_config(suffix, port))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_includes_wildcard_address_for_suffix() {
        let cfg = build_config("test", 53053);
        assert!(cfg.contains("port=53053"));
        assert!(cfg.contains("address=/.test/127.0.0.1"));
        assert!(cfg.contains("listen-address=127.0.0.1"));
        assert!(cfg.contains("no-daemon"));
    }

    #[test]
    fn config_swaps_suffix_cleanly() {
        let cfg = build_config("local", 53053);
        assert!(cfg.contains("address=/.local/127.0.0.1"));
        assert!(!cfg.contains("/.test/"));
    }

    #[test]
    fn write_config_writes_a_file_we_can_read_back() {
        let path = write_config("test", 53054).unwrap();
        let contents = std::fs::read_to_string(&path).unwrap();
        assert!(contents.contains("port=53054"));
        assert!(contents.contains("address=/.test/127.0.0.1"));
    }
}
