//! Generates `dnsmasq.conf` from the registry's domain suffix.
//!
//! Format reference: `man 8 dnsmasq` and the `address=` directive.
//! `address=/.<suffix>/127.0.0.1` makes dnsmasq answer with
//! `127.0.0.1` for any A query whose name ends in `.<suffix>` —
//! e.g. `address=/.test/127.0.0.1` matches `myapp.test`,
//! `api.myapp.test`, and so on.
//!
//! The OS resolver must route queries for the specific suffix to this dnsmasq
//! instance: macOS uses `/etc/resolver/<suffix>`, while Linux uses a
//! systemd-resolved drop-in. Until that resolver wiring exists, dnsmasq runs
//! but no normal application resolutions flow through it.

use std::path::PathBuf;

use crate::registry::DnsmasqSettings;

/// Build the dnsmasq config string. `port` is the UDP port the daemon
/// listens on locally — must be the same port the platform resolver file will
/// eventually reference. `settings` carries the user-tunable cache / TTL
/// directives; the rest of the config is fixed for safety.
pub fn build_config(suffix: &str, port: u16, settings: &DnsmasqSettings) -> String {
    // `bind-interfaces` + `listen-address=127.0.0.1` keeps dnsmasq off
    // any non-loopback interface. `no-daemon` keeps the process in the
    // foreground so Tauri's child-process supervisor sees it cleanly.
    // `no-resolv` + `no-hosts` keep the daemon from inheriting the
    // system resolver chain (we only want it to answer for our suffix).
    // `domain-needed` + `bogus-priv` are belt-and-suspenders to
    // suppress accidental forwarding of unqualified or RFC1918-reverse
    // queries to upstream nameservers.
    let settings = settings.sanitised();
    let mut cfg = format!(
        "# Generated by PortBay — do not edit by hand.\n\
         # Regenerated whenever the registry's domain_suffix or dnsmasq\n\
         # settings change.\n\
         port={port}\n\
         no-daemon\n\
         no-resolv\n\
         no-hosts\n\
         domain-needed\n\
         bogus-priv\n\
         listen-address=127.0.0.1\n\
         bind-interfaces\n\
         cache-size={cache}\n\
         local-ttl={ttl}\n\
         address=/.{suffix}/127.0.0.1\n",
        cache = settings.cache_size,
        ttl = settings.local_ttl,
    );
    if settings.disable_negative_cache {
        cfg.push_str("no-negcache\n");
    }
    cfg
}

/// Default location for the generated config. `<data_dir>/PortBay/dnsmasq.conf`.
pub fn default_config_path() -> std::io::Result<PathBuf> {
    let mut dir = dirs::data_dir()
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no data dir"))?;
    dir.push("PortBay");
    std::fs::create_dir_all(&dir)?;
    Ok(dir.join("dnsmasq.conf"))
}

/// Write the config to the default path; return where it landed.
pub fn write_config(
    suffix: &str,
    port: u16,
    settings: &DnsmasqSettings,
) -> std::io::Result<PathBuf> {
    let path = default_config_path()?;
    std::fs::write(&path, build_config(suffix, port, settings))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_includes_wildcard_address_for_suffix() {
        let cfg = build_config("test", 53053, &DnsmasqSettings::default());
        assert!(cfg.contains("port=53053"));
        assert!(cfg.contains("address=/.test/127.0.0.1"));
        assert!(cfg.contains("listen-address=127.0.0.1"));
        assert!(cfg.contains("no-daemon"));
    }

    #[test]
    fn config_swaps_suffix_cleanly() {
        let cfg = build_config("local", 53053, &DnsmasqSettings::default());
        assert!(cfg.contains("address=/.local/127.0.0.1"));
        assert!(!cfg.contains("/.test/"));
    }

    #[test]
    fn multi_label_suffix_renders_a_single_wildcard() {
        let cfg = build_config("portbay.test", 53053, &DnsmasqSettings::default());
        assert!(cfg.contains("address=/.portbay.test/127.0.0.1"));
    }

    #[test]
    fn default_settings_emit_cache_and_ttl_directives() {
        let cfg = build_config("test", 53053, &DnsmasqSettings::default());
        assert!(cfg.contains("cache-size=150"));
        assert!(cfg.contains("local-ttl=0"));
        // Negative-cache is on by default → no `no-negcache` directive.
        assert!(!cfg.contains("no-negcache"));
    }

    #[test]
    fn custom_settings_render_directives() {
        let settings = DnsmasqSettings {
            cache_size: 500,
            local_ttl: 30,
            disable_negative_cache: true,
        };
        let cfg = build_config("test", 53053, &settings);
        assert!(cfg.contains("cache-size=500"));
        assert!(cfg.contains("local-ttl=30"));
        assert!(cfg.contains("no-negcache"));
    }

    #[test]
    fn out_of_range_settings_are_clamped_in_output() {
        let settings = DnsmasqSettings {
            cache_size: u16::MAX,
            local_ttl: u32::MAX,
            disable_negative_cache: false,
        };
        let cfg = build_config("test", 53053, &settings);
        assert!(cfg.contains(&format!(
            "cache-size={}",
            crate::registry::types::MAX_DNS_CACHE_SIZE
        )));
        assert!(cfg.contains(&format!(
            "local-ttl={}",
            crate::registry::types::MAX_DNS_LOCAL_TTL
        )));
    }

    #[test]
    fn write_config_writes_a_file_we_can_read_back() {
        let path = write_config("test", 53054, &DnsmasqSettings::default()).unwrap();
        let contents = std::fs::read_to_string(&path).unwrap();
        assert!(contents.contains("port=53054"));
        assert!(contents.contains("address=/.test/127.0.0.1"));
    }
}
