//! Launch-command generation for mobile projects (iOS / Android / Flutter /
//! Expo).
//!
//! PortBay's Play/Stop is a Process Compose process: Play runs a long-running
//! `command`, Stop sends it SIGTERM. Native mobile "runs" aren't naturally
//! long-running (build → install → launch is one-shot), so each command here
//! ends by **attaching to a live stream** — `simctl launch --console-pty`,
//! `adb logcat`, `flutter run`, or the Expo Metro server. The stream keeps the
//! PC process alive while the app runs, and Stop tears it down.
//!
//! Device selection is resolved **at run time inside the shell** (not here), so
//! the command is self-contained and reflects whatever simulator/emulator the
//! user actually has booted: an explicit `MobileRunConfig.device` wins,
//! otherwise the first booted device, otherwise the first available one. This
//! keeps PC-config generation pure (no `simctl`/`adb` I/O in the reconcile
//! tick) and lets the same registry entry work across machines. A pinned
//! destination that's gone is an explicit, actionable error — the script never
//! silently substitutes another device (the Expo-Orbit bug we design against).
//!
//! Pinned-device id forms (written by the rail's destination picker, see
//! `crate::mobile_targets`): an iOS simulator udid, an adb serial, or
//! `avd:<name>` for an Android AVD the script boots first.
//!
//! Phase markers: the scripts echo line-anchored `::portbay::phase=<p>` /
//! `::portbay::device=<id>` markers between steps. `crate::mobile_phase`
//! parses them out of the log tail into the truthful run sub-state the UI
//! shows (booted → building → installing → launching → connected) instead of
//! flipping to "Running" while xcodebuild is still compiling.
//!
//! Stop metadata: before attaching, the iOS/Android scripts write
//! `.portbay-build/run-meta` (PLATFORM/DEV/BID or SER/PKG) so
//! [`terminate_app`] can kill the *app* on Stop — PC's SIGTERM only detaches
//! the log stream, which would leave the app running on the simulator
//! (Xcode's Stop kills the app; ours now does too).
//!
//! The shell here targets `/bin/sh` (what Process Compose invokes) and is kept
//! to one logical line via `&&`/`;`/`if…fi` so it round-trips through the YAML
//! `command` scalar cleanly. Paths are referenced relative to the project dir
//! (PC sets `working_dir` to the project path), sidestepping spaces in the
//! absolute path.

use std::collections::HashMap;
use std::path::Path;

use crate::registry::{MobileRunConfig, Project, ProjectType};

/// Relative path (inside the project dir) of the pid file `flutter run`
/// maintains for the session. Hot reload/restart signal this pid (SIGUSR1 /
/// SIGUSR2) — Flutter's documented headless reload mechanism, which works
/// through Process Compose where stdin doesn't.
pub const FLUTTER_PID_FILE: &str = ".portbay-flutter.pid";

/// Relative path of the stop metadata the iOS/Android scripts write.
pub const RUN_META_FILE: &str = ".portbay-build/run-meta";

/// Build the Play command for a mobile project, or `None` if the kind isn't a
/// mobile kind. The returned string is handed to Process Compose as the
/// process `command` and run from the project directory.
pub fn launch_command(p: &Project) -> Option<String> {
    let cfg = p.mobile_run.clone().unwrap_or_default();
    launch_command_for(p.kind, &cfg)
}

/// Core: the Play command for a mobile `kind` + its run config. Shared by the
/// reconciler (via [`launch_command`]) and the folder detector, so a mobile
/// project launches identically whether the command is generated at reconcile
/// time or stamped onto the registry at add time. Returns `None` for
/// non-mobile kinds.
pub fn launch_command_for(kind: ProjectType, cfg: &MobileRunConfig) -> Option<String> {
    match kind {
        ProjectType::Xcode => Some(ios_command(cfg)),
        ProjectType::Android => Some(android_command(cfg)),
        ProjectType::Flutter => Some(flutter_command(cfg)),
        ProjectType::Expo => Some(expo_command(cfg)),
        _ => None,
    }
}

/// True when `cmd` is a launch script generated by this module (any version):
/// only our scripts emit `::portbay::phase=` markers. The PC-config layer uses
/// this to regenerate a project's add-time `start_command` stamp instead of
/// running it verbatim forever — otherwise generator fixes never reach
/// already-added projects (kitabi: the registry kept replaying the old
/// first-listed-scheme script after the fallback was fixed). A user-written
/// custom command never contains the marker, so it still wins.
pub fn is_generated_launch(cmd: &str) -> bool {
    cmd.contains("::portbay::phase=")
}

/// True for kinds whose Play is a mobile simulator/emulator launch rather than
/// an HTTP dev server. Used by the PC-config layer to skip HTTP readiness
/// probes (a simulator launch never answers an HTTP GET).
pub fn is_mobile_kind(kind: ProjectType) -> bool {
    matches!(
        kind,
        ProjectType::Xcode | ProjectType::Android | ProjectType::Flutter | ProjectType::Expo
    )
}

/// Single-quote a value for safe interpolation into the `/bin/sh` command.
/// Empty stays empty (callers test for that). `'` is escaped the POSIX way.
fn sq(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Does this pinned device id look like a CoreSimulator UDID (uppercase UUID)?
/// Drives the Flutter prelude that boots a shut-down simulator before
/// `flutter run` (flutter refuses ids that aren't currently bootable).
fn looks_like_sim_udid(id: &str) -> bool {
    id.len() == 36
        && id.chars().all(|c| c.is_ascii_hexdigit() || c == '-')
        && id.chars().filter(|&c| c == '-').count() == 4
}

/// Does this pinned device id look like a *physical* iOS device UDID?
/// Modern devices: `00008120-001964AC0CB8C01E` (8 hex, dash, 16 hex);
/// pre-2018 devices: 40 hex chars, no dash. Distinct from the 36-char
/// 4-dash simulator UUIDs, so the iOS launch script can branch on the form.
fn looks_like_ios_device_udid(id: &str) -> bool {
    let modern = id.len() == 25
        && id.as_bytes().get(8) == Some(&b'-')
        && id.chars().enumerate().all(|(i, c)| {
            if i == 8 {
                c == '-'
            } else {
                c.is_ascii_hexdigit()
            }
        });
    let legacy = id.len() == 40 && id.chars().all(|c| c.is_ascii_hexdigit());
    modern || legacy
}

// ---------------------------------------------------------------------------
// iOS (Xcode)
// ---------------------------------------------------------------------------

/// iOS launch: a pinned physical-device UDID takes the devicectl path; a
/// simulator UDID (or no pin) takes the simctl path. Both resolve
/// project/workspace and scheme at run time.
fn ios_command(cfg: &MobileRunConfig) -> String {
    // Pinned device udid/name (empty → auto). `-configuration` follows the
    // flavor when set, else Debug — and `auto_config` records that Debug was a
    // default, not a choice, so the device script may override it for Flutter
    // hosts (a pinned configuration is always honoured verbatim).
    let pinned_dev = cfg.device.clone().unwrap_or_default();
    let pinned_scheme = cfg.target.clone().unwrap_or_default();
    let (config, auto_config) = match cfg.flavor.as_deref() {
        Some(f) if !f.is_empty() => (f.to_string(), false),
        _ => ("Debug".to_string(), true),
    };

    if looks_like_ios_device_udid(&pinned_dev) {
        return ios_device_command(&pinned_dev, &pinned_scheme, &config, auto_config);
    }
    ios_simulator_command(&pinned_dev, &pinned_scheme, &config)
}

/// Shared shell fragment: resolve `$PF` (workspace/project flag) and `$SCHEME`.
///
/// Scheme fallback (no pin): prefer the scheme named like the workspace /
/// project itself (`Runner.xcworkspace` → `Runner`) — in a CocoaPods
/// workspace `xcodebuild -list` enumerates every pod's scheme alphabetically,
/// so "first listed" lands on an arbitrary pod (kitabi: built
/// `adaptive_platform_ui` instead of `Runner`, producing no .app). Only when
/// no same-named scheme exists fall back to the first listed one.
fn ios_project_resolve(pinned_scheme: &str) -> String {
    format!(
        "WS=$(ls -d *.xcworkspace 2>/dev/null | head -1); \
         PROJ=$(ls -d *.xcodeproj 2>/dev/null | head -1); \
         if [ -n \"$WS\" ]; then PF=\"-workspace $WS\"; else PF=\"-project $PROJ\"; fi; \
         SCHEME={pinned_scheme}; \
         if [ -z \"$SCHEME\" ]; then \
           if [ -n \"$WS\" ]; then BASE=$(basename \"$WS\" .xcworkspace); else BASE=$(basename \"$PROJ\" .xcodeproj); fi; \
           SCHEMES=$(xcodebuild $PF -list 2>/dev/null | awk '/Schemes:/{{f=1;next}} f{{if(!NF)exit; sub(/^ */,\"\"); print}}'); \
           SCHEME=$(printf '%s\\n' \"$SCHEMES\" | grep -Fx \"$BASE\" | head -1); \
           if [ -z \"$SCHEME\" ]; then SCHEME=$(printf '%s\\n' \"$SCHEMES\" | head -1); fi; \
         fi",
        pinned_scheme = sq(pinned_scheme),
    )
}

/// boot a simulator → build the scheme → install → launch attached to the
/// console. Resolves device at run time (pinned → first booted → first
/// available iPhone). The `.app` is picked from the `$CONFIG-iphonesimulator`
/// products dir specifically — a device build or another configuration's
/// stale product may sit next to it. `NSUnbufferedIO=YES` makes xcodebuild
/// write build output through the pipe per line instead of block-buffering,
/// so the log viewer narrates the (long) build phase live.
fn ios_simulator_command(pinned_dev: &str, pinned_scheme: &str, config: &str) -> String {
    format!(
        "set -e; \
         echo '::portbay::phase=resolving-device'; \
         {project_resolve}; \
         DEV={pinned_dev}; \
         if [ -n \"$DEV\" ] && ! xcrun simctl list devices available | grep -q \"$DEV\"; then \
           echo \"pinned simulator $DEV is unavailable — pick another destination in PortBay\" >&2; exit 1; fi; \
         if [ -z \"$DEV\" ]; then DEV=$(xcrun simctl list devices booted | grep -oE '[0-9A-Fa-f-]{{36}}' | head -1); fi; \
         if [ -z \"$DEV\" ]; then DEV=$(xcrun simctl list devices available | grep -i iPhone | grep -oE '[0-9A-Fa-f-]{{36}}' | head -1); fi; \
         if [ -z \"$DEV\" ]; then echo 'no iOS simulator found — create one in Xcode' >&2; exit 1; fi; \
         echo \"::portbay::device=$DEV\"; \
         echo '::portbay::phase=booting-device'; \
         xcrun simctl boot \"$DEV\" 2>/dev/null || true; \
         open -a Simulator || true; \
         CONFIG={config}; \
         echo '::portbay::phase=building'; \
         NSUnbufferedIO=YES xcodebuild $PF -scheme \"$SCHEME\" -configuration \"$CONFIG\" -destination \"id=$DEV\" -derivedDataPath .portbay-build build; \
         APP=$(find .portbay-build/Build/Products -maxdepth 2 -path \"*$CONFIG-iphonesimulator*\" -name '*.app' | head -1); \
         if [ -z \"$APP\" ]; then echo \"build succeeded but produced no .app — scheme '$SCHEME' is probably not the app scheme; pin the right one under Advanced → Scheme in PortBay\" >&2; exit 1; fi; \
         BID=$(/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' \"$APP/Info.plist\"); \
         echo '::portbay::phase=installing'; \
         xcrun simctl install \"$DEV\" \"$APP\"; \
         printf 'PLATFORM=ios\\nDEV=%s\\nBID=%s\\n' \"$DEV\" \"$BID\" > {run_meta}; \
         echo '::portbay::phase=launching'; \
         exec xcrun simctl launch --console-pty \"$DEV\" \"$BID\"",
        project_resolve = ios_project_resolve(pinned_scheme),
        pinned_dev = sq(pinned_dev),
        config = sq(config),
        run_meta = RUN_META_FILE,
    )
}

/// Physical iOS device via `devicectl` (Xcode 15+): signing-aware build
/// (`-allowProvisioningUpdates` lets Xcode's automatic signing mint/refresh
/// the dev profile) → `devicectl device install app` → `devicectl device
/// process launch --console`, which stays attached for the run's lifetime
/// *and forwards catchable signals to the app* — so PC's SIGTERM on Stop
/// terminates the app on the device, matching Xcode's Stop. The reachability
/// pre-check keeps the never-substitute promise: an unplugged pinned phone is
/// an explicit error, not a fallback.
///
/// Flutter-host auto-Release (`auto_config` = no pinned configuration): a
/// *debug* Flutter app aborts at launch on a physical iOS 14+ device unless
/// Flutter tooling/Xcode is attached (the Dart JIT needs a debugger — the
/// kitabi signal-11 crash), and devicectl launches standalone. When the Xcode
/// project is a Flutter ios/ host (`../pubspec.yaml`), the script builds
/// Release instead — runnable standalone, like Xcode's ⌘R for release testing,
/// just without hot reload. Pinning a configuration in Advanced overrides.
/// The `.app` find is scoped to `$CONFIG-iphoneos` so a stale Debug product
/// next to the fresh Release one can't be picked.
fn ios_device_command(udid: &str, pinned_scheme: &str, config: &str, auto_config: bool) -> String {
    let flutter_release_switch = if auto_config {
        "if [ \"$CONFIG\" = 'Debug' ] && [ -f ../pubspec.yaml ]; then \
           echo 'Flutter host detected: debug builds cannot launch standalone on a device — building Release instead (pin a configuration in Advanced to override)'; \
           CONFIG='Release'; \
         fi; "
    } else {
        ""
    };
    format!(
        "set -e; \
         echo '::portbay::phase=resolving-device'; \
         {project_resolve}; \
         DEV={udid}; \
         if ! xcrun devicectl device info details --device \"$DEV\" >/dev/null 2>&1; then \
           echo \"device $DEV is not reachable — connect it by cable (unlock + Trust) or join the same Wi-Fi, then run again\" >&2; exit 1; fi; \
         echo \"::portbay::device=$DEV\"; \
         CONFIG={config}; \
         {flutter_release_switch}\
         echo '::portbay::phase=building'; \
         NSUnbufferedIO=YES xcodebuild $PF -scheme \"$SCHEME\" -configuration \"$CONFIG\" -destination \"id=$DEV\" -allowProvisioningUpdates -derivedDataPath .portbay-build build; \
         APP=$(find .portbay-build/Build/Products -maxdepth 2 -path \"*$CONFIG-iphoneos*\" -name '*.app' | head -1); \
         if [ -z \"$APP\" ]; then echo \"build succeeded but produced no .app — scheme '$SCHEME' is probably not the app scheme; pin the right one under Advanced → Scheme in PortBay\" >&2; exit 1; fi; \
         BID=$(/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' \"$APP/Info.plist\"); \
         echo '::portbay::phase=installing'; \
         xcrun devicectl device install app --device \"$DEV\" \"$APP\"; \
         APPNAME=$(basename \"$APP\" .app); \
         printf 'PLATFORM=ios-device\\nDEV=%s\\nBID=%s\\nAPPNAME=%s\\n' \"$DEV\" \"$BID\" \"$APPNAME\" > {run_meta}; \
         echo '::portbay::phase=launching'; \
         exec xcrun devicectl device process launch --console --terminate-existing --device \"$DEV\" \"$BID\"",
        project_resolve = ios_project_resolve(pinned_scheme),
        udid = sq(udid),
        config = sq(config),
        flutter_release_switch = flutter_release_switch,
        run_meta = RUN_META_FILE,
    )
}

// ---------------------------------------------------------------------------
// Android (Gradle)
// ---------------------------------------------------------------------------

/// Shell fragment that resolves `$SER` for a running emulator backing `$AVD`,
/// boots the AVD when none is, and fails honestly when it can't.
fn android_avd_resolve(avd: &str) -> String {
    format!(
        "AVD={avd}; SER=''; \
         for S in $(adb devices | awk 'NR>1 && $2==\"device\"{{print $1}}' | grep '^emulator-' || true); do \
           N=$(adb -s \"$S\" emu avd name 2>/dev/null | head -1 | tr -d '\\r'); \
           if [ \"$N\" = \"$AVD\" ]; then SER=$S; break; fi; done; \
         if [ -z \"$SER\" ]; then echo '::portbay::phase=booting-device'; \
           (emulator -avd \"$AVD\" >/dev/null 2>&1 &); adb wait-for-device; \
           SER=$(adb devices | awk 'NR>1 && $2==\"device\"{{print $1; exit}}'); fi; \
         if [ -z \"$SER\" ]; then echo \"could not boot AVD $AVD — start it in Android Studio and retry\" >&2; exit 1; fi",
        avd = sq(avd),
    )
}

/// ensure a device/emulator → `gradlew install*` → launch the monkey
/// LAUNCHER intent → attach to `adb logcat`. Reads `applicationId` from the
/// app module's gradle for the launch intent. `--console=plain` stops Gradle
/// from drawing its rich in-place progress console (which buffers and
/// redraws ANSI blocks on a pipe) so build output reaches the log per line.
fn android_command(cfg: &MobileRunConfig) -> String {
    // Pinned serial or `avd:<name>` (empty → auto). A product `flavor`
    // prefixes the install task (`installStagingDebug`); the build *type* is
    // always Debug here, so a flavor of "debug"/"release" is treated as the
    // type — not doubled into `installDebugDebug`. No flavor → `installDebug`.
    let pinned = cfg.device.clone().unwrap_or_default();
    let product_flavor = cfg.flavor.as_deref().map(str::trim).filter(|f| {
        !f.is_empty() && !f.eq_ignore_ascii_case("debug") && !f.eq_ignore_ascii_case("release")
    });
    let install_task = match product_flavor {
        Some(f) => format!("install{}Debug", capitalize(f)),
        None => "installDebug".to_string(),
    };
    let module = match cfg.target.as_deref() {
        Some(t) if !t.is_empty() => t.to_string(),
        _ => "app".to_string(),
    };

    // Resolve $SER per pin form. A pinned serial that isn't connected is an
    // explicit error — never a silent fallback to some other device.
    let resolve = if let Some(avd) = pinned.strip_prefix("avd:") {
        android_avd_resolve(avd)
    } else if !pinned.is_empty() {
        format!(
            "SER={pinned}; \
             if ! adb devices | awk 'NR>1 && $2==\"device\"{{print $1}}' | grep -qx \"$SER\"; then \
               echo \"pinned device $SER is not connected — pick another destination in PortBay\" >&2; exit 1; fi",
            pinned = sq(&pinned),
        )
    } else {
        "SER=$(adb devices | awk 'NR>1 && $2==\"device\"{print $1; exit}'); \
         if [ -z \"$SER\" ]; then AVD=$(emulator -list-avds 2>/dev/null | grep -v '^INFO' | head -1); \
           if [ -n \"$AVD\" ]; then echo '::portbay::phase=booting-device'; \
             (emulator -avd \"$AVD\" >/dev/null 2>&1 &); adb wait-for-device; \
             SER=$(adb devices | awk 'NR>1 && $2==\"device\"{print $1; exit}'); \
           else echo 'no Android device/emulator — create an AVD in Android Studio' >&2; exit 1; fi; \
         fi"
            .to_string()
    };

    format!(
        "set -e; \
         echo '::portbay::phase=resolving-device'; \
         {resolve}; \
         echo \"::portbay::device=$SER\"; \
         GR=./gradlew; [ -x \"$GR\" ] || GR=gradlew; \
         echo '::portbay::phase=building'; \
         \"$GR\" --console=plain :{module}:{install_task}; \
         PKG=$(grep -RhoE 'applicationId[ =\"]+[a-zA-Z0-9_.]+' {module}/build.gradle* 2>/dev/null | grep -oE '[a-zA-Z0-9_.]+$' | head -1); \
         mkdir -p .portbay-build; \
         printf 'PLATFORM=android\\nSER=%s\\nPKG=%s\\n' \"$SER\" \"$PKG\" > {run_meta}; \
         echo '::portbay::phase=launching'; \
         if [ -n \"$PKG\" ]; then adb -s \"$SER\" shell monkey -p \"$PKG\" -c android.intent.category.LAUNCHER 1 || true; fi; \
         echo '::portbay::phase=connected'; \
         exec adb -s \"$SER\" logcat",
        resolve = resolve,
        module = module,
        install_task = install_task,
        run_meta = RUN_META_FILE,
    )
}

// ---------------------------------------------------------------------------
// Flutter
// ---------------------------------------------------------------------------

/// `flutter run` stays attached for the session (hot-reload host). Honour a
/// pinned device and flavor when set; a pinned shut-down simulator/AVD is
/// booted first (flutter only runs on live targets). The pid file enables
/// hot reload/restart via SIGUSR1/SIGUSR2.
fn flutter_command(cfg: &MobileRunConfig) -> String {
    let pinned = cfg.device.clone().unwrap_or_default();
    let mut cmd = format!(
        "echo '::portbay::phase=resolving-device'; rm -f {pid}; ",
        pid = FLUTTER_PID_FILE
    );

    // Device argument for `flutter run`, after any boot prelude.
    let device_arg: Option<String> = if let Some(avd) = pinned.strip_prefix("avd:") {
        cmd.push_str(&android_avd_resolve(avd));
        cmd.push_str("; ");
        Some("-d \"$SER\"".to_string())
    } else if looks_like_sim_udid(&pinned) {
        cmd.push_str(&format!(
            "echo '::portbay::phase=booting-device'; \
             xcrun simctl boot {udid} 2>/dev/null || true; \
             open -a Simulator || true; ",
            udid = sq(&pinned),
        ));
        Some(format!("-d {}", sq(&pinned)))
    } else if !pinned.is_empty() {
        Some(format!("-d {}", sq(&pinned)))
    } else {
        None
    };

    cmd.push_str(&format!(
        "exec flutter run --pid-file {pid}",
        pid = FLUTTER_PID_FILE
    ));
    if let Some(d) = device_arg {
        cmd.push_str(&format!(" {d}"));
    }
    if let Some(f) = cfg.flavor.as_deref().filter(|s| !s.is_empty()) {
        cmd.push_str(&format!(" --flavor {}", sq(f)));
    }
    if let Some(t) = cfg.target.as_deref().filter(|s| !s.is_empty()) {
        cmd.push_str(&format!(" -t {}", sq(t)));
    }
    cmd
}

// ---------------------------------------------------------------------------
// Expo
// ---------------------------------------------------------------------------

/// Expo's Metro dev server is itself long-running, so Play maps to it directly.
/// A pinned `device` of `ios`/`android` auto-opens that simulator on start.
fn expo_command(cfg: &MobileRunConfig) -> String {
    let mut cmd = String::from("exec npx expo start");
    match cfg.device.as_deref().map(str::trim) {
        Some("ios") => cmd.push_str(" --ios"),
        Some("android") => cmd.push_str(" --android"),
        _ => {}
    }
    cmd
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

// ---------------------------------------------------------------------------
// Stop semantics + hot reload plumbing
// ---------------------------------------------------------------------------

/// Kill the *app* a mobile run launched, using the `run-meta` the script wrote
/// — Xcode's Stop semantics. PC's SIGTERM only tears down the attached stream
/// (console-pty / logcat); without this the app keeps running on the
/// simulator/device. Best-effort and blocking (callers use the blocking pool);
/// the meta file is consumed so a stale file can't kill a later run's app.
pub fn terminate_app(project_dir: &Path) {
    let meta_path = project_dir.join(RUN_META_FILE);
    let Ok(text) = std::fs::read_to_string(&meta_path) else {
        return;
    };
    let kv = parse_run_meta(&text);
    match kv.get("PLATFORM").map(String::as_str) {
        Some("ios") => {
            if let (Some(dev), Some(bid)) = (kv.get("DEV"), kv.get("BID")) {
                if !dev.is_empty() && !bid.is_empty() {
                    let _ = std::process::Command::new("xcrun")
                        .args(["simctl", "terminate", dev, bid])
                        .output();
                }
            }
        }
        // Physical device: the primary stop path is `devicectl … launch
        // --console` forwarding PC's SIGTERM to the app. This fallback covers
        // the escalation case (PC SIGKILLs a hung devicectl after its grace
        // window — nothing gets forwarded): look the app's pid up on the
        // device and terminate it there.
        Some("ios-device") => {
            if let (Some(dev), Some(appname)) = (kv.get("DEV"), kv.get("APPNAME")) {
                if !dev.is_empty() && !appname.is_empty() {
                    if let Some(pid) = device_app_pid(dev, appname) {
                        let _ = std::process::Command::new("xcrun")
                            .args([
                                "devicectl",
                                "device",
                                "process",
                                "terminate",
                                "--device",
                                dev,
                                "--pid",
                                &pid.to_string(),
                            ])
                            .output();
                    }
                }
            }
        }
        Some("android") => {
            if let (Some(ser), Some(pkg)) = (kv.get("SER"), kv.get("PKG")) {
                if !ser.is_empty() && !pkg.is_empty() {
                    if let Some(adb) = crate::mobile_targets::adb_bin() {
                        let _ = std::process::Command::new(adb)
                            .args(["-s", ser, "shell", "am", "force-stop", pkg])
                            .output();
                    }
                }
            }
        }
        _ => {}
    }
    let _ = std::fs::remove_file(&meta_path);
}

/// Pid of `<appname>.app/<appname>` running on a physical device, via
/// `devicectl device info processes` (JSON goes to a temp file — that's
/// devicectl's only scripting interface). Best-effort: any failure → None.
fn device_app_pid(dev: &str, appname: &str) -> Option<u32> {
    let tmp = std::env::temp_dir().join(format!("portbay-devprocs-{}.json", std::process::id()));
    let ok = std::process::Command::new("xcrun")
        .args([
            "devicectl",
            "device",
            "info",
            "processes",
            "--device",
            dev,
            "--json-output",
        ])
        .arg(&tmp)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if !ok {
        let _ = std::fs::remove_file(&tmp);
        return None;
    }
    let json = std::fs::read_to_string(&tmp).unwrap_or_default();
    let _ = std::fs::remove_file(&tmp);
    parse_device_app_pid(&json, appname)
}

pub(crate) fn parse_device_app_pid(json: &str, appname: &str) -> Option<u32> {
    let v: serde_json::Value = serde_json::from_str(json).ok()?;
    let procs = v.pointer("/result/runningProcesses")?.as_array()?;
    let needle = format!("/{appname}.app/{appname}");
    procs.iter().find_map(|p| {
        let exe = p.get("executable")?.as_str()?;
        if exe.ends_with(&needle) {
            p.get("processIdentifier")?.as_u64().map(|pid| pid as u32)
        } else {
            None
        }
    })
}

/// Parse the `KEY=VALUE` lines of a run-meta file.
pub(crate) fn parse_run_meta(text: &str) -> HashMap<String, String> {
    text.lines()
        .filter_map(|l| {
            let (k, v) = l.split_once('=')?;
            Some((k.trim().to_string(), v.trim().to_string()))
        })
        .collect()
}

/// Pid of the live `flutter run` session for a project, from the pid file the
/// launch command maintains. `None` when no session is running (or the file is
/// stale-empty).
pub fn flutter_run_pid(project_dir: &Path) -> Option<i32> {
    let text = std::fs::read_to_string(project_dir.join(FLUTTER_PID_FILE)).ok()?;
    let pid: i32 = text.trim().parse().ok()?;
    (pid > 1).then_some(pid)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::ProjectType;

    #[test]
    fn is_mobile_kind_covers_the_four_targets() {
        for k in [
            ProjectType::Xcode,
            ProjectType::Android,
            ProjectType::Flutter,
            ProjectType::Expo,
        ] {
            assert!(is_mobile_kind(k));
        }
        assert!(!is_mobile_kind(ProjectType::Next));
        assert!(!is_mobile_kind(ProjectType::Php));
    }

    #[test]
    fn ios_command_builds_installs_and_attaches_console() {
        let cmd = ios_command(&MobileRunConfig::default());
        assert!(cmd.contains("xcodebuild"));
        assert!(cmd.contains("simctl install"));
        assert!(cmd.contains("simctl launch --console-pty"));
        // auto device discovery present when none pinned
        assert!(cmd.contains("simctl list devices booted"));
        // build output must stream per line, not in 4–8 KB pipe chunks
        assert!(cmd.contains("NSUnbufferedIO=YES xcodebuild"));
    }

    #[test]
    fn ios_command_emits_phase_markers_and_run_meta() {
        let cmd = ios_command(&MobileRunConfig::default());
        for marker in [
            "::portbay::phase=resolving-device",
            "::portbay::phase=booting-device",
            "::portbay::phase=building",
            "::portbay::phase=installing",
            "::portbay::phase=launching",
            "::portbay::device=$DEV",
        ] {
            assert!(cmd.contains(marker), "missing {marker}");
        }
        assert!(cmd.contains(RUN_META_FILE));
    }

    #[test]
    fn ios_command_honours_pinned_scheme_and_device() {
        let cfg = MobileRunConfig {
            target: Some("App".into()),
            device: Some("ABC-123".into()),
            flavor: None,
        };
        let cmd = ios_command(&cfg);
        assert!(cmd.contains("SCHEME='App'"));
        assert!(cmd.contains("DEV='ABC-123'"));
        // A gone pinned device errors out instead of silently substituting.
        assert!(cmd.contains("pick another destination"));
    }

    #[test]
    fn ios_scheme_fallback_prefers_container_named_scheme() {
        // Unpinned scheme: the fallback must try the workspace/project
        // basename before settling for the first `-list` entry — first-listed
        // in a CocoaPods workspace is an arbitrary pod, not the app.
        let cmd = ios_command(&MobileRunConfig::default());
        assert!(cmd.contains("basename \"$WS\" .xcworkspace"));
        assert!(cmd.contains("basename \"$PROJ\" .xcodeproj"));
        assert!(cmd.contains("grep -Fx \"$BASE\""));
    }

    #[test]
    fn ios_commands_fail_honestly_when_no_app_is_produced() {
        // Both destinations: a wrong-scheme build "succeeds" without an .app;
        // the script must say so instead of a cryptic PlistBuddy error.
        let sim = ios_command(&MobileRunConfig::default());
        let dev = ios_command(&MobileRunConfig {
            device: Some("00008120-001964AC0CB8C01E".into()),
            ..Default::default()
        });
        for cmd in [&sim, &dev] {
            assert!(cmd.contains("produced no .app"));
        }
    }

    #[test]
    fn android_command_installs_and_attaches_logcat() {
        let cmd = android_command(&MobileRunConfig::default());
        assert!(cmd.contains(":app:installDebug"));
        assert!(cmd.contains("adb -s \"$SER\" logcat"));
        assert!(cmd.contains("emulator -list-avds"));
        // plain console: Gradle's rich progress UI buffers/redraws on a pipe
        assert!(cmd.contains("--console=plain"));
        // Markers + explicit connected (logcat attach follows the launch).
        assert!(cmd.contains("::portbay::phase=building"));
        assert!(cmd.contains("::portbay::phase=connected"));
        assert!(cmd.contains(RUN_META_FILE));
    }

    #[test]
    fn android_pinned_serial_never_silently_substitutes() {
        let cfg = MobileRunConfig {
            device: Some("emulator-5554".into()),
            ..Default::default()
        };
        let cmd = android_command(&cfg);
        assert!(cmd.contains("SER='emulator-5554'"));
        assert!(cmd.contains("is not connected — pick another destination"));
    }

    #[test]
    fn android_pinned_avd_boots_by_name() {
        let cfg = MobileRunConfig {
            device: Some("avd:Pixel_8_API_35".into()),
            ..Default::default()
        };
        let cmd = android_command(&cfg);
        assert!(cmd.contains("AVD='Pixel_8_API_35'"));
        assert!(cmd.contains("emu avd name"));
        assert!(cmd.contains("emulator -avd \"$AVD\""));
    }

    #[test]
    fn android_flavor_selects_variant_install_task() {
        let cfg = MobileRunConfig {
            flavor: Some("staging".into()),
            target: None,
            device: None,
        };
        assert!(android_command(&cfg).contains("installStagingDebug"));
    }

    #[test]
    fn android_build_type_flavor_is_not_doubled() {
        // The folder detector passes flavor="debug" (the build *type*); it must
        // not become `installDebugDebug`.
        let cfg = MobileRunConfig {
            flavor: Some("debug".into()),
            target: None,
            device: None,
        };
        let cmd = android_command(&cfg);
        assert!(cmd.contains(":app:installDebug"));
        assert!(!cmd.contains("installDebugDebug"));
    }

    #[test]
    fn flutter_and_expo_are_long_running() {
        let f = flutter_command(&MobileRunConfig::default());
        assert!(f.contains("exec flutter run"));
        assert!(f.contains("--pid-file .portbay-flutter.pid"));
        assert_eq!(
            expo_command(&MobileRunConfig::default()),
            "exec npx expo start"
        );
        let cfg = MobileRunConfig {
            device: Some("ios".into()),
            ..Default::default()
        };
        assert!(expo_command(&cfg).ends_with("--ios"));
    }

    #[test]
    fn flutter_pinned_sim_udid_boots_the_simulator_first() {
        let cfg = MobileRunConfig {
            device: Some("01234567-89AB-CDEF-0123-456789ABCDEF".into()),
            ..Default::default()
        };
        let cmd = flutter_command(&cfg);
        assert!(cmd.contains("xcrun simctl boot '01234567-89AB-CDEF-0123-456789ABCDEF'"));
        assert!(cmd.contains("-d '01234567-89AB-CDEF-0123-456789ABCDEF'"));
    }

    #[test]
    fn flutter_pinned_avd_resolves_to_a_serial() {
        let cfg = MobileRunConfig {
            device: Some("avd:Pixel_8".into()),
            ..Default::default()
        };
        let cmd = flutter_command(&cfg);
        assert!(cmd.contains("AVD='Pixel_8'"));
        assert!(cmd.contains("-d \"$SER\""));
    }

    #[test]
    fn flutter_plain_device_id_passes_through() {
        let cfg = MobileRunConfig {
            device: Some("emulator-5554".into()),
            flavor: Some("staging".into()),
            target: Some("lib/main_staging.dart".into()),
        };
        let cmd = flutter_command(&cfg);
        assert!(cmd.contains("-d 'emulator-5554'"));
        assert!(cmd.contains("--flavor 'staging'"));
        assert!(cmd.contains("-t 'lib/main_staging.dart'"));
    }

    #[test]
    fn run_meta_parses_key_values() {
        let kv = parse_run_meta("PLATFORM=ios\nDEV=AAAA-1111\nBID=com.example.app\n");
        assert_eq!(kv.get("PLATFORM").map(String::as_str), Some("ios"));
        assert_eq!(kv.get("DEV").map(String::as_str), Some("AAAA-1111"));
        assert_eq!(kv.get("BID").map(String::as_str), Some("com.example.app"));
    }

    #[test]
    fn looks_like_sim_udid_matches_uuids_only() {
        assert!(looks_like_sim_udid("01234567-89AB-CDEF-0123-456789ABCDEF"));
        assert!(!looks_like_sim_udid("emulator-5554"));
        assert!(!looks_like_sim_udid("avd:Pixel_8"));
        assert!(!looks_like_sim_udid("iPhone 16"));
    }

    #[test]
    fn ios_device_udid_forms_are_distinguished_from_simulators() {
        // Modern physical (8-16 form) and legacy 40-hex are devices…
        assert!(looks_like_ios_device_udid("00008120-001964AC0CB8C01E"));
        assert!(looks_like_ios_device_udid(&"a".repeat(40)));
        // …simulator UUIDs and everything else are not.
        assert!(!looks_like_ios_device_udid(
            "01234567-89AB-CDEF-0123-456789ABCDEF"
        ));
        assert!(!looks_like_ios_device_udid("emulator-5554"));
        assert!(!looks_like_ios_device_udid("iPhone 16"));
    }

    #[test]
    fn ios_pinned_physical_device_takes_the_devicectl_path() {
        let cfg = MobileRunConfig {
            device: Some("00008120-001964AC0CB8C01E".into()),
            target: Some("Runner".into()),
            flavor: None,
        };
        let cmd = ios_command(&cfg);
        // Signing-aware build + devicectl install/launch, console-attached so
        // PC's SIGTERM forwards to the app on Stop.
        assert!(cmd.contains("-allowProvisioningUpdates"));
        assert!(cmd.contains("devicectl device install app"));
        assert!(cmd.contains("devicectl device process launch --console --terminate-existing"));
        // Device builds must pick the active configuration's iphoneos .app,
        // never a stale sim build or another configuration's product.
        assert!(cmd.contains("-path \"*$CONFIG-iphoneos*\""));
        // Reachability pre-check keeps the never-substitute promise.
        assert!(cmd.contains("is not reachable"));
        assert!(cmd.contains("PLATFORM=ios-device"));
        // No simulator plumbing on this path.
        assert!(!cmd.contains("simctl boot"));
    }

    #[test]
    fn ios_simulator_build_only_picks_simulator_products() {
        let cmd = ios_command(&MobileRunConfig::default());
        assert!(cmd.contains("-path \"*$CONFIG-iphonesimulator*\""));
        assert!(!cmd.contains("iphoneos*"));
    }

    #[test]
    fn ios_device_default_config_auto_releases_for_flutter_hosts() {
        // No pinned configuration: a Flutter ios/ host (../pubspec.yaml) gets
        // Release — a standalone debug Flutter launch aborts on-device (the
        // Dart JIT needs attached tooling). Non-Flutter projects keep Debug:
        // the switch is conditional on the pubspec probe.
        let cmd = ios_command(&MobileRunConfig {
            device: Some("00008120-001964AC0CB8C01E".into()),
            ..Default::default()
        });
        assert!(cmd.contains("[ -f ../pubspec.yaml ]"));
        assert!(cmd.contains("CONFIG='Release'"));
        assert!(cmd.contains("building Release instead"));
    }

    #[test]
    fn ios_device_pinned_config_is_honoured_verbatim() {
        // An explicit configuration is a user choice — never auto-switched,
        // even on a Flutter host.
        let cmd = ios_command(&MobileRunConfig {
            device: Some("00008120-001964AC0CB8C01E".into()),
            flavor: Some("Debug".into()),
            ..Default::default()
        });
        assert!(cmd.contains("CONFIG='Debug'"));
        assert!(!cmd.contains("pubspec.yaml"));
    }

    #[test]
    fn device_app_pid_parses_devicectl_processes_json() {
        let json = r#"{"result":{"runningProcesses":[
            {"processIdentifier":1,"executable":"file:///sbin/launchd"},
            {"processIdentifier":4321,"executable":"file:///private/var/containers/Bundle/Application/ABC/Runner.app/Runner"}
        ]}}"#;
        assert_eq!(parse_device_app_pid(json, "Runner"), Some(4321));
        assert_eq!(parse_device_app_pid(json, "Other"), None);
        assert_eq!(parse_device_app_pid("not json", "Runner"), None);
    }
}
