//! macOS menu-bar tray (P3 — Tray Mode).
//!
//! Surface:
//! - A persistent menu-bar icon that updates colour to reflect the
//!   aggregate health of all PortBay-managed projects:
//!     gray  → daemon down or no projects
//!     blue  → at least one project starting
//!     green → all running projects healthy
//!     red   → at least one project crashed / port-conflicted
//! - A left/right-click menu listing every registered project with a
//!   Start/Stop/Restart/Open submenu, plus the global controls (Stop all,
//!   Show window, Preferences, Quit).
//!
//! Architecture:
//! - The tray icon + menu live in `AppState::tray` (held in a
//!   `Mutex<Option<TrayHandle>>`).
//! - The status poller (`commands::events`) calls `refresh_from_poll()`
//!   each tick when it observes the project list or aggregate status
//!   has changed. That call rebuilds the menu and swaps the icon — both
//!   on the main thread via Tauri's main-thread guarantees on
//!   `TrayIcon::set_menu` / `set_icon`.
//! - The menu's event handler dispatches into the same lifecycle
//!   commands the GUI uses (`pc_client.start/stop/restart`, `opener` for
//!   "Open in browser") so the tray and the dashboard cannot drift.
//!
//! Icons are PNGs in `icons/tray/` generated by
//! `scripts/generate-tray-icons.sh`. They're embedded at compile-time
//! via `include_bytes!` so a packaged .app never has to look for them
//! on disk.

use std::sync::Mutex;

use tauri::menu::{Menu, MenuBuilder, MenuEvent};
use tauri::tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use tauri::{image::Image, AppHandle, Emitter, LogicalPosition, Manager, PhysicalPosition, Rect};

use crate::process_compose::ProjectStatus;
use crate::registry::Project;
use crate::state::AppState;

/// Label of the popover webview that owns the rich tray UI. Must match
/// the `label` in `tauri.conf.json` `app.windows[]`.
pub const PANEL_WINDOW_LABEL: &str = "tray-panel";

/// Configured popover dimensions (must match tauri.conf.json).
const PANEL_WIDTH: f64 = 360.0;
const PANEL_HEIGHT: f64 = 480.0;
/// Vertical gap between the menu-bar icon's bottom edge and the popover
/// top edge — enough air so the popover doesn't overlap the menu bar
/// shadow but tight enough to read as anchored to the icon.
const PANEL_GAP: f64 = 6.0;

/// Tray icon id — used to look the tray handle back up via
/// `AppHandle::tray_by_id`, though we cache it in `AppState` for hot-path
/// updates.
const TRAY_ID: &str = "portbay-main";

/// Channel name the frontend listens on for the one-time "still running
/// in the menu bar" toast. Layered alongside the existing
/// `portbay://status` channel — same URI convention.
pub const CLOSE_TOAST_CHANNEL: &str = "portbay://close-to-menubar-hint";

/// Global menu-item ids on the fallback right-click menu. The rich
/// surface lives in the popover webview; this menu is a thin
/// accessibility hatch.
const ID_SHOW_WINDOW: &str = "show-window";
const ID_PREFERENCES: &str = "preferences";
const ID_QUIT: &str = "quit";

/// Aggregate health used to pick the tray-icon colour. The variants
/// follow project-status precedence: any crash > any starting > otherwise
/// the daemon is healthy (or idle if no projects are running).
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum AggregateStatus {
    /// PC daemon unreachable, or registry empty, or every project is stopped.
    Idle,
    /// At least one project is currently coming up; nothing crashed.
    Starting,
    /// At least one project is running and none are unhealthy/crashed.
    Running,
    /// At least one project is in a crashed / port-conflict state.
    Error,
}

impl AggregateStatus {
    pub fn from_iter<I: IntoIterator<Item = ProjectStatus>>(statuses: I) -> Self {
        let mut any_error = false;
        let mut any_starting = false;
        let mut any_running = false;
        for s in statuses {
            match s {
                ProjectStatus::Crashed | ProjectStatus::PortConflict => any_error = true,
                ProjectStatus::Starting => any_starting = true,
                ProjectStatus::Running | ProjectStatus::Unhealthy => any_running = true,
                ProjectStatus::Stopped => {}
            }
        }
        if any_error {
            Self::Error
        } else if any_starting {
            Self::Starting
        } else if any_running {
            Self::Running
        } else {
            Self::Idle
        }
    }

    /// Human-readable tooltip suffix surfaced when the user hovers the
    /// tray icon. Pairs with the project count for context.
    fn tooltip_label(self) -> &'static str {
        match self {
            Self::Idle => "idle",
            Self::Starting => "starting",
            Self::Running => "all healthy",
            Self::Error => "needs attention",
        }
    }
}

/// Compile-time icon payloads. Embedded so the bundled .app cannot drift
/// from the binary — runtime swap is a memory-only operation.
const ICON_IDLE: &[u8] = include_bytes!("../icons/tray/idle.png");
const ICON_STARTING: &[u8] = include_bytes!("../icons/tray/starting.png");
const ICON_RUNNING: &[u8] = include_bytes!("../icons/tray/running.png");
const ICON_ERROR: &[u8] = include_bytes!("../icons/tray/error.png");

fn icon_for(status: AggregateStatus) -> Image<'static> {
    let bytes = match status {
        AggregateStatus::Idle => ICON_IDLE,
        AggregateStatus::Starting => ICON_STARTING,
        AggregateStatus::Running => ICON_RUNNING,
        AggregateStatus::Error => ICON_ERROR,
    };
    Image::from_bytes(bytes).expect("embedded tray icon PNG is malformed — rebuild from scripts/generate-tray-icons.sh")
}

/// Snapshot held in `AppState` so the poller can recompute the icon
/// colour in O(1) without re-reading state. `last_status` gates the
/// icon swap — we only touch the tray when the aggregate changed,
/// which keeps `tray.set_icon` from running every status tick for
/// nothing.
#[derive(Default)]
pub struct TrayHandle {
    pub icon: Option<TrayIcon>,
    pub last_status: Option<AggregateStatus>,
}

/// Hold the tray inside a single mutex so the poller can read/swap
/// atomically. Public so `AppState` can embed it; everything else
/// goes through the helpers below.
pub type TrayState = Mutex<TrayHandle>;

/// Initialise the tray icon. Idempotent — calling twice replaces the
/// existing icon (used when the user re-enables the "Show menu bar
/// icon" preference after disabling it).
///
/// Returns Ok on success. A None visible-tray failure is treated as a
/// degraded mode — the dashboard keeps working — and is only logged.
pub fn install(app: &AppHandle) -> tauri::Result<()> {
    let menu = build_fallback_menu(app)?;
    let icon = TrayIconBuilder::with_id(TRAY_ID)
        .icon(icon_for(AggregateStatus::Idle))
        .icon_as_template(false) // we ship 4 distinct colours; let macOS keep them
        .tooltip("PortBay — idle")
        .menu(&menu)
        // Left-click opens the popover webview (handled in
        // `handle_tray_event`). Right / Ctrl-click drops to the native
        // fallback menu — accessibility hatch + a path to Quit when
        // the popover misbehaves.
        .show_menu_on_left_click(false)
        .on_menu_event(handle_menu_event)
        .on_tray_icon_event(handle_tray_event)
        .build(app)?;

    let state: tauri::State<AppState> = app.state();
    let mut tray = state.tray.lock().expect("tray mutex poisoned");
    tray.icon = Some(icon);
    tray.last_status = Some(AggregateStatus::Idle);
    Ok(())
}

/// Remove the tray entirely. The user toggled "Show menu bar icon" off.
/// Re-enabling calls `install` again with a fresh menu.
pub fn uninstall(app: &AppHandle) {
    let state: tauri::State<AppState> = app.state();
    let mut tray = state.tray.lock().expect("tray mutex poisoned");
    if let Some(icon) = tray.icon.take() {
        // Hiding is sufficient; the icon drops on scope exit which the
        // platform layer treats as removal.
        let _ = icon.set_visible(false);
    }
    tray.last_status = None;
    // Suppress unused warning when called from settings before install
    let _ = app;
}

/// Driven by the status poller. Computes the aggregate status from the
/// current project + status snapshot and rebuilds the menu + icon only
/// if either changed since the last call.
///
/// `projects` is the canonical registry ordering. `statuses` is a
/// lookup of project-id → current ProjectStatus from the most recent
/// PC observation. A project id that's absent from `statuses` is
/// treated as Stopped (matches the dashboard's behaviour).
pub fn refresh(
    app: &AppHandle,
    projects: &[Project],
    statuses: &std::collections::HashMap<String, ProjectStatus>,
) {
    let state: tauri::State<AppState> = app.state();
    let aggregate = AggregateStatus::from_iter(
        projects
            .iter()
            .map(|p| statuses.get(p.id.as_str()).copied().unwrap_or(ProjectStatus::Stopped)),
    );

    // Lock just long enough to compare + decide; release before any
    // tray IPC. `TrayIcon` methods are documented as main-thread safe
    // so this re-entry into the platform layer is fine.
    let (need_icon, icon_clone) = {
        let mut tray = state.tray.lock().expect("tray mutex poisoned");
        let icon = match tray.icon.as_ref() {
            Some(i) => i.clone(),
            None => return, // tray disabled by preference
        };
        let need_icon = tray.last_status != Some(aggregate);
        if need_icon {
            tray.last_status = Some(aggregate);
        }
        (need_icon, icon)
    };

    if need_icon {
        if let Err(e) = icon_clone.set_icon(Some(icon_for(aggregate))) {
            tracing::warn!(error = %e, "tray.set_icon failed");
        }
        let tooltip = format!(
            "PortBay — {} ({} project{})",
            aggregate.tooltip_label(),
            projects.len(),
            if projects.len() == 1 { "" } else { "s" }
        );
        let _ = icon_clone.set_tooltip(Some(tooltip));
    }
}

/// Right-click fallback menu. Three items — the rich list lives in
/// the popover webview.
fn build_fallback_menu(app: &AppHandle) -> tauri::Result<Menu<tauri::Wry>> {
    MenuBuilder::new(app)
        .text(ID_SHOW_WINDOW, "Show PortBay window")
        .text(ID_PREFERENCES, "Preferences…")
        .separator()
        .text(ID_QUIT, "Quit PortBay")
        .build()
}

/// Dispatcher for the fallback menu. Per-project actions and Stop-all
/// moved into the popover; the menu no longer carries any project ids.
fn handle_menu_event(app: &AppHandle, event: MenuEvent) {
    match event.id.as_ref() {
        ID_QUIT => {
            // Hide the popover first so it doesn't flash on top of a
            // disappearing main window during shutdown.
            if let Some(panel) = app.get_webview_window(PANEL_WINDOW_LABEL) {
                let _ = panel.hide();
            }
            // app.exit destroys all windows, which fires our
            // `WindowEvent::Destroyed` shutdown sweep in lib.rs.
            app.exit(0);
        }
        ID_SHOW_WINDOW => {
            show_main_window(app);
        }
        ID_PREFERENCES => {
            show_main_window(app);
            // Frontend listens to `portbay://nav` to push routes.
            let _ = app.emit("portbay://nav", "/settings");
        }
        _ => {}
    }
}

/// macOS tray click handler. Left-click toggles the popover anchored
/// to the icon position; double-click also brings the main window
/// forward (useful when the user has hidden the window with
/// close-to-menu-bar). Right-click is delegated to the platform —
/// the OS draws our fallback menu since `show_menu_on_left_click`
/// is false.
fn handle_tray_event(tray: &TrayIcon, event: TrayIconEvent) {
    match event {
        TrayIconEvent::Click {
            button: MouseButton::Left,
            button_state: MouseButtonState::Up,
            position,
            rect,
            ..
        } => {
            toggle_panel(tray.app_handle(), position, rect);
        }
        TrayIconEvent::DoubleClick {
            button: MouseButton::Left,
            ..
        } => {
            // Bring the main window forward; the single-click already
            // showed the popover, so this is the "give me the dashboard"
            // escape hatch.
            show_main_window(tray.app_handle());
        }
        _ => {}
    }
}

/// Toggle the popover window's visibility, anchoring it under the
/// menu-bar icon. If the panel is already visible, hide it
/// (sticky-click-to-dismiss). Otherwise position + show + focus.
///
/// `click` and `rect` arrive in physical pixels from the platform; we
/// convert to logical via the panel's scale factor so the 360×480
/// window size stays consistent across Retina and non-Retina displays.
fn toggle_panel(app: &AppHandle, click: PhysicalPosition<f64>, rect: Rect) {
    let Some(panel) = app.get_webview_window(PANEL_WINDOW_LABEL) else {
        tracing::warn!("tray-panel window not found — popover unavailable");
        return;
    };

    // If visible, treat the click as dismiss. `is_visible` is a cheap
    // call against the platform layer; no need to track state in Rust.
    if matches!(panel.is_visible(), Ok(true)) {
        let _ = panel.hide();
        return;
    }

    let scale = panel.scale_factor().unwrap_or(1.0);
    // Anchor: centre horizontally on the icon, drop the panel below
    // it. macOS's coordinate origin is top-left, so "below" is
    // `click.y + gap`. Rect.size is a Size enum that may be physical
    // or logical depending on the platform — `to_logical` normalises.
    let icon_size = rect.size.to_logical::<f64>(scale);
    let logical_click_x = click.x / scale;
    let logical_click_y = click.y / scale;

    let mut target_x = logical_click_x + icon_size.width / 2.0 - PANEL_WIDTH / 2.0;
    let target_y = logical_click_y + PANEL_GAP;

    // Keep the panel on-screen if the menu-bar icon sits near a
    // screen edge. Query the panel's current monitor for bounds.
    if let Ok(Some(monitor)) = panel.current_monitor() {
        let mon_pos = monitor.position();
        let mon_size = monitor.size();
        let mon_logical_x = mon_pos.x as f64 / scale;
        let mon_logical_w = mon_size.width as f64 / scale;
        let min_x = mon_logical_x + 4.0;
        let max_x = mon_logical_x + mon_logical_w - PANEL_WIDTH - 4.0;
        if target_x < min_x {
            target_x = min_x;
        }
        if target_x > max_x {
            target_x = max_x;
        }
    }

    let _ = panel.set_position(LogicalPosition::new(target_x, target_y));
    let _ = panel.show();
    let _ = panel.set_focus();

    // The hidden window may have lost its 'always on top' flag in some
    // window-manager edge cases. Re-assert so the popover floats over
    // other apps even when the main window is in the background.
    let _ = panel.set_always_on_top(true);

    // Suppress unused warning — PANEL_HEIGHT is the contract with
    // tauri.conf.json; we don't need to set it here, but exporting the
    // constant keeps both surfaces in lockstep.
    let _ = PANEL_HEIGHT;
}

/// Hide the popover. Wired into the `Focused(false)` event in lib.rs
/// so a click outside the panel closes it.
pub fn hide_panel(app: &AppHandle) {
    if let Some(panel) = app.get_webview_window(PANEL_WINDOW_LABEL) {
        let _ = panel.hide();
    }
}

/// Reveal + focus the main window. Used by the tray's Show-window item
/// and by the icon double-click handler.
pub fn show_main_window(app: &AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_aggregate_is_idle() {
        assert_eq!(AggregateStatus::from_iter([]), AggregateStatus::Idle);
    }

    #[test]
    fn all_stopped_is_idle() {
        let s = [ProjectStatus::Stopped, ProjectStatus::Stopped];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Idle);
    }

    #[test]
    fn any_starting_with_running_is_starting_not_running() {
        // Precedence guard: even if other projects are happy, the user
        // should see the "transition in progress" colour rather than
        // green so the tray reflects in-flight work.
        let s = [ProjectStatus::Running, ProjectStatus::Starting];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Starting);
    }

    #[test]
    fn any_crashed_overrides_everything_else() {
        let s = [
            ProjectStatus::Running,
            ProjectStatus::Starting,
            ProjectStatus::Crashed,
        ];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Error);
    }

    #[test]
    fn port_conflict_is_an_error_state() {
        let s = [ProjectStatus::Running, ProjectStatus::PortConflict];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Error);
    }

    #[test]
    fn unhealthy_counts_toward_running_not_error() {
        // Unhealthy means "process is up but failing its probe". That's
        // a degraded state, not a crash — the existing dashboard treats
        // it as a yellow attention state. We collapse it into the
        // running colour (green) at the tray level so we don't claim
        // red for an issue the user can't fix from the menu bar.
        let s = [ProjectStatus::Running, ProjectStatus::Unhealthy];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Running);
    }

}
