//! macOS menu-bar tray (P3 — Tray Mode).
//!
//! Surface:
//! - A persistent menu-bar icon that updates colour to reflect the
//!   aggregate health of all PortBay-managed projects:
//!     gray  → daemon down or no projects
//!     blue  → at least one project starting
//!     green → all running projects healthy
//!     red   → at least one project crashed / port-conflicted
//! - A left/right-click menu listing every registered project with a
//!   Start/Stop/Restart/Open submenu, plus the global controls (Stop all,
//!   Show window, Preferences, Quit).
//!
//! Architecture:
//! - The tray icon + menu live in `AppState::tray` (held in a
//!   `Mutex<Option<TrayHandle>>`).
//! - The status poller (`commands::events`) calls `refresh_from_poll()`
//!   each tick when it observes the project list or aggregate status
//!   has changed. That call rebuilds the menu and swaps the icon — both
//!   on the main thread via Tauri's main-thread guarantees on
//!   `TrayIcon::set_menu` / `set_icon`.
//! - The menu's event handler dispatches into the same lifecycle
//!   commands the GUI uses (`pc_client.start/stop/restart`, `opener` for
//!   "Open in browser") so the tray and the dashboard cannot drift.
//!
//! Icons are PNGs in `icons/tray/` generated by
//! `scripts/generate-tray-icons.sh`. They're embedded at compile-time
//! via `include_bytes!` so a packaged .app never has to look for them
//! on disk.

use std::sync::Mutex;

use tauri::menu::{Menu, MenuBuilder, MenuEvent, SubmenuBuilder};
use tauri::tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use tauri::{image::Image, AppHandle, Emitter, Manager};
use tauri_plugin_opener::OpenerExt;

use crate::process_compose::ProjectStatus;
use crate::registry::Project;
use crate::state::AppState;

/// Tray icon id — used to look the tray handle back up via
/// `AppHandle::tray_by_id`, though we cache it in `AppState` for hot-path
/// updates.
const TRAY_ID: &str = "portbay-main";

/// Channel name the frontend listens on for the one-time "still running
/// in the menu bar" toast. Layered alongside the existing
/// `portbay://status` channel — same URI convention.
pub const CLOSE_TOAST_CHANNEL: &str = "portbay://close-to-menubar-hint";

/// Menu item id prefix for per-project rows. The id encodes the action
/// and the project id so the single `on_menu_event` callback can
/// dispatch without an out-of-band lookup table.
const PROJECT_PREFIX: &str = "project:";

/// Global menu-item ids — kept as constants so the build site and the
/// handler can't drift.
const ID_SHOW_WINDOW: &str = "show-window";
const ID_PREFERENCES: &str = "preferences";
const ID_STOP_ALL: &str = "stop-all";
const ID_QUIT: &str = "quit";

/// Aggregate health used to pick the tray-icon colour. The variants
/// follow project-status precedence: any crash > any starting > otherwise
/// the daemon is healthy (or idle if no projects are running).
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum AggregateStatus {
    /// PC daemon unreachable, or registry empty, or every project is stopped.
    Idle,
    /// At least one project is currently coming up; nothing crashed.
    Starting,
    /// At least one project is running and none are unhealthy/crashed.
    Running,
    /// At least one project is in a crashed / port-conflict state.
    Error,
}

impl AggregateStatus {
    pub fn from_iter<I: IntoIterator<Item = ProjectStatus>>(statuses: I) -> Self {
        let mut any_error = false;
        let mut any_starting = false;
        let mut any_running = false;
        for s in statuses {
            match s {
                ProjectStatus::Crashed | ProjectStatus::PortConflict => any_error = true,
                ProjectStatus::Starting => any_starting = true,
                ProjectStatus::Running | ProjectStatus::Unhealthy => any_running = true,
                ProjectStatus::Stopped => {}
            }
        }
        if any_error {
            Self::Error
        } else if any_starting {
            Self::Starting
        } else if any_running {
            Self::Running
        } else {
            Self::Idle
        }
    }

    /// Human-readable tooltip suffix surfaced when the user hovers the
    /// tray icon. Pairs with the project count for context.
    fn tooltip_label(self) -> &'static str {
        match self {
            Self::Idle => "idle",
            Self::Starting => "starting",
            Self::Running => "all healthy",
            Self::Error => "needs attention",
        }
    }
}

/// Compile-time icon payloads. Embedded so the bundled .app cannot drift
/// from the binary — runtime swap is a memory-only operation.
const ICON_IDLE: &[u8] = include_bytes!("../icons/tray/idle.png");
const ICON_STARTING: &[u8] = include_bytes!("../icons/tray/starting.png");
const ICON_RUNNING: &[u8] = include_bytes!("../icons/tray/running.png");
const ICON_ERROR: &[u8] = include_bytes!("../icons/tray/error.png");

fn icon_for(status: AggregateStatus) -> Image<'static> {
    let bytes = match status {
        AggregateStatus::Idle => ICON_IDLE,
        AggregateStatus::Starting => ICON_STARTING,
        AggregateStatus::Running => ICON_RUNNING,
        AggregateStatus::Error => ICON_ERROR,
    };
    Image::from_bytes(bytes).expect("embedded tray icon PNG is malformed — rebuild from scripts/generate-tray-icons.sh")
}

/// Snapshot held in `AppState` so the poller can recompute the menu /
/// icon in O(1) without re-reading state. `last_status` and `last_count`
/// gate the rebuild — we only touch the tray when something changed,
/// which keeps `tray.set_menu` from running 30× per minute for nothing.
#[derive(Default)]
pub struct TrayHandle {
    pub icon: Option<TrayIcon>,
    pub last_status: Option<AggregateStatus>,
    pub last_signature: Option<String>,
}

/// Hold the tray inside a single mutex so the poller can read/swap
/// atomically. Public so `AppState` can embed it; everything else
/// goes through the helpers below.
pub type TrayState = Mutex<TrayHandle>;

/// Initialise the tray icon. Idempotent — calling twice replaces the
/// existing icon (used when the user re-enables the "Show menu bar
/// icon" preference after disabling it).
///
/// Returns Ok on success. A None visible-tray failure is treated as a
/// degraded mode — the dashboard keeps working — and is only logged.
pub fn install(app: &AppHandle) -> tauri::Result<()> {
    let menu = build_menu(app, &[])?;
    let icon = TrayIconBuilder::with_id(TRAY_ID)
        .icon(icon_for(AggregateStatus::Idle))
        .icon_as_template(false) // we ship 4 distinct colours; let macOS keep them
        .tooltip("PortBay — idle")
        .menu(&menu)
        .show_menu_on_left_click(true)
        .on_menu_event(handle_menu_event)
        .on_tray_icon_event(handle_tray_event)
        .build(app)?;

    let state: tauri::State<AppState> = app.state();
    let mut tray = state.tray.lock().expect("tray mutex poisoned");
    tray.icon = Some(icon);
    tray.last_status = Some(AggregateStatus::Idle);
    tray.last_signature = Some(String::new());
    Ok(())
}

/// Remove the tray entirely. The user toggled "Show menu bar icon" off.
/// Re-enabling calls `install` again with a fresh menu.
pub fn uninstall(app: &AppHandle) {
    let state: tauri::State<AppState> = app.state();
    let mut tray = state.tray.lock().expect("tray mutex poisoned");
    if let Some(icon) = tray.icon.take() {
        // Hiding is sufficient; the icon drops on scope exit which the
        // platform layer treats as removal.
        let _ = icon.set_visible(false);
    }
    tray.last_status = None;
    tray.last_signature = None;
    // Suppress unused warning when called from settings before install
    let _ = app;
}

/// Driven by the status poller. Computes the aggregate status from the
/// current project + status snapshot and rebuilds the menu + icon only
/// if either changed since the last call.
///
/// `projects` is the canonical registry ordering. `statuses` is a
/// lookup of project-id → current ProjectStatus from the most recent
/// PC observation. A project id that's absent from `statuses` is
/// treated as Stopped (matches the dashboard's behaviour).
pub fn refresh(
    app: &AppHandle,
    projects: &[Project],
    statuses: &std::collections::HashMap<String, ProjectStatus>,
) {
    let state: tauri::State<AppState> = app.state();
    let aggregate = AggregateStatus::from_iter(
        projects
            .iter()
            .map(|p| statuses.get(p.id.as_str()).copied().unwrap_or(ProjectStatus::Stopped)),
    );
    let signature = build_signature(projects, statuses);

    // Lock just long enough to compare + decide; release before any
    // tray IPC. `TrayIcon` methods are documented as main-thread safe
    // so this re-entry into the platform layer is fine.
    let (need_menu, need_icon, icon_clone) = {
        let mut tray = state.tray.lock().expect("tray mutex poisoned");
        let icon = match tray.icon.as_ref() {
            Some(i) => i.clone(),
            None => return, // tray disabled by preference
        };
        let need_menu = tray.last_signature.as_deref() != Some(signature.as_str());
        let need_icon = tray.last_status != Some(aggregate);
        if need_menu {
            tray.last_signature = Some(signature);
        }
        if need_icon {
            tray.last_status = Some(aggregate);
        }
        (need_menu, need_icon, icon)
    };

    if need_menu {
        match build_menu(app, projects_with_statuses(projects, statuses).as_slice()) {
            Ok(menu) => {
                if let Err(e) = icon_clone.set_menu(Some(menu)) {
                    tracing::warn!(error = %e, "tray.set_menu failed");
                }
            }
            Err(e) => tracing::warn!(error = %e, "tray menu rebuild failed"),
        }
    }
    if need_icon {
        if let Err(e) = icon_clone.set_icon(Some(icon_for(aggregate))) {
            tracing::warn!(error = %e, "tray.set_icon failed");
        }
        let tooltip = format!(
            "PortBay — {} ({} project{})",
            aggregate.tooltip_label(),
            projects.len(),
            if projects.len() == 1 { "" } else { "s" }
        );
        let _ = icon_clone.set_tooltip(Some(tooltip));
    }
}

/// Collapse the inputs into a fingerprint string. Used solely to gate
/// the `set_menu` call — when nothing material changed (same projects
/// in same order with same statuses), the menu rebuild is skipped.
fn build_signature(
    projects: &[Project],
    statuses: &std::collections::HashMap<String, ProjectStatus>,
) -> String {
    let mut s = String::with_capacity(projects.len() * 24);
    for p in projects {
        let st = statuses
            .get(p.id.as_str())
            .copied()
            .unwrap_or(ProjectStatus::Stopped);
        s.push_str(p.id.as_str());
        s.push(':');
        s.push_str(p.name.as_str());
        s.push(':');
        s.push_str(status_glyph(st));
        s.push('\n');
    }
    s
}

fn projects_with_statuses<'a>(
    projects: &'a [Project],
    statuses: &std::collections::HashMap<String, ProjectStatus>,
) -> Vec<(&'a Project, ProjectStatus)> {
    projects
        .iter()
        .map(|p| {
            (
                p,
                statuses
                    .get(p.id.as_str())
                    .copied()
                    .unwrap_or(ProjectStatus::Stopped),
            )
        })
        .collect()
}

/// One-character status glyph prefixed to the project name in the
/// tray menu. macOS native menus don't support coloured pills, so this
/// is our visible status hint. Matches the dashboard's vocabulary at a
/// glance.
fn status_glyph(s: ProjectStatus) -> &'static str {
    match s {
        ProjectStatus::Running => "●",
        ProjectStatus::Starting => "◐",
        ProjectStatus::Unhealthy => "◑",
        ProjectStatus::Crashed | ProjectStatus::PortConflict => "✕",
        ProjectStatus::Stopped => "○",
    }
}

/// Build the menu from the current project snapshot. Pulled out of
/// `install` so the same code path serves the cold-boot menu and every
/// subsequent rebuild.
fn build_menu(
    app: &AppHandle,
    projects: &[(&Project, ProjectStatus)],
) -> tauri::Result<Menu<tauri::Wry>> {
    let mut builder = MenuBuilder::new(app)
        .text("portbay-header", "PortBay")
        .separator();

    if projects.is_empty() {
        builder = builder.text("no-projects", "No projects yet — add one from the dashboard");
    } else {
        for (project, status) in projects {
            let label = format!("{}  {}", status_glyph(*status), project.name);
            let id = project.id.as_str();
            let is_running = matches!(
                status,
                ProjectStatus::Running | ProjectStatus::Starting | ProjectStatus::Unhealthy
            );
            let submenu = SubmenuBuilder::new(app, label)
                .text(
                    format!("{PROJECT_PREFIX}start:{id}"),
                    if is_running { "Start (already running)" } else { "Start" },
                )
                .text(format!("{PROJECT_PREFIX}stop:{id}"), "Stop")
                .text(format!("{PROJECT_PREFIX}restart:{id}"), "Restart")
                .separator()
                .text(format!("{PROJECT_PREFIX}open:{id}"), "Open in browser")
                .text(format!("{PROJECT_PREFIX}reveal:{id}"), "Reveal in Finder")
                .build()?;
            builder = builder.item(&submenu);
        }
    }

    builder
        .separator()
        .text(ID_STOP_ALL, "Stop all projects")
        .text(ID_SHOW_WINDOW, "Show PortBay window")
        .text(ID_PREFERENCES, "Preferences…")
        .separator()
        .text(ID_QUIT, "Quit PortBay")
        .build()
}

/// Single menu-event dispatcher. Per-project ids are encoded as
/// `project:<action>:<id>` so the parser is a single split.
fn handle_menu_event(app: &AppHandle, event: MenuEvent) {
    let id = event.id.as_ref();
    match id {
        ID_QUIT => {
            // app.exit destroys all windows, which fires our
            // `WindowEvent::Destroyed` shutdown sweep in lib.rs.
            app.exit(0);
        }
        ID_SHOW_WINDOW => {
            show_main_window(app);
        }
        ID_PREFERENCES => {
            show_main_window(app);
            // Frontend listens to `portbay://nav` to push routes.
            let _ = app.emit("portbay://nav", "/settings");
        }
        ID_STOP_ALL => {
            let handle = app.clone();
            tauri::async_runtime::spawn(async move {
                let state: tauri::State<AppState> = handle.state();
                let Ok(client) = state.pc_client() else { return };
                if let Ok(processes) = client.processes().await {
                    for p in processes {
                        if p.is_running {
                            let _ = client.stop(&p.name).await;
                        }
                    }
                }
            });
        }
        other if other.starts_with(PROJECT_PREFIX) => {
            // Strip the prefix and split into `<action>:<project_id>`.
            let payload = &other[PROJECT_PREFIX.len()..];
            let Some((action, project_id)) = payload.split_once(':') else {
                return;
            };
            dispatch_project_action(app, action, project_id);
        }
        _ => {}
    }
}

/// Project-level actions. Each spawns onto Tauri's async runtime so the
/// menu handler returns immediately and the macOS UI thread isn't
/// blocked by HTTP round-trips to PC.
fn dispatch_project_action(app: &AppHandle, action: &str, project_id: &str) {
    let project_id = project_id.to_string();
    let action = action.to_string();
    let handle = app.clone();
    tauri::async_runtime::spawn(async move {
        let state: tauri::State<AppState> = handle.state();
        match action.as_str() {
            "start" => {
                if let Ok(client) = state.pc_client() {
                    let _ = client.start(&project_id).await;
                }
            }
            "stop" => {
                if let Ok(client) = state.pc_client() {
                    let _ = client.stop(&project_id).await;
                }
            }
            "restart" => {
                if let Ok(client) = state.pc_client() {
                    let _ = client.restart(&project_id).await;
                }
            }
            "open" => {
                // Resolve the project's URL from the registry and ask
                // the system to open it. Mirrors `commands::lifecycle::open_project`.
                if let Ok(registry) = crate::commands::projects::load_registry(&state) {
                    if let Some(project) = registry
                        .list_projects()
                        .iter()
                        .find(|p| p.id.as_str() == project_id)
                    {
                        let scheme = if project.https { "https" } else { "http" };
                        let url = format!("{scheme}://{}", project.hostname);
                        let _ = handle.opener().open_url(url, None::<&str>);
                    }
                }
            }
            "reveal" => {
                if let Ok(registry) = crate::commands::projects::load_registry(&state) {
                    if let Some(project) = registry
                        .list_projects()
                        .iter()
                        .find(|p| p.id.as_str() == project_id)
                    {
                        let _ = handle.opener().open_path(
                            project.path.to_string_lossy().to_string(),
                            None::<&str>,
                        );
                    }
                }
            }
            _ => {}
        }
    });
}

/// macOS convention: right-click and left-click both reveal the menu
/// (we set `show_menu_on_left_click(true)` so the platform handles
/// that case). We additionally treat a *double* left-click as "bring
/// the main window forward" — handy when the user has hidden the
/// window via close-to-menu-bar.
fn handle_tray_event(tray: &TrayIcon, event: TrayIconEvent) {
    if let TrayIconEvent::DoubleClick {
        button: MouseButton::Left,
        ..
    } = event
    {
        show_main_window(tray.app_handle());
    } else if let TrayIconEvent::Click {
        button: MouseButton::Left,
        button_state: MouseButtonState::Up,
        ..
    } = event
    {
        // No-op: the platform displays the attached menu automatically.
        // Kept here so the pattern is explicit when future actions land.
    }
}

/// Reveal + focus the main window. Used by the tray's Show-window item
/// and by the icon double-click handler.
pub fn show_main_window(app: &AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_aggregate_is_idle() {
        assert_eq!(AggregateStatus::from_iter([]), AggregateStatus::Idle);
    }

    #[test]
    fn all_stopped_is_idle() {
        let s = [ProjectStatus::Stopped, ProjectStatus::Stopped];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Idle);
    }

    #[test]
    fn any_starting_with_running_is_starting_not_running() {
        // Precedence guard: even if other projects are happy, the user
        // should see the "transition in progress" colour rather than
        // green so the tray reflects in-flight work.
        let s = [ProjectStatus::Running, ProjectStatus::Starting];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Starting);
    }

    #[test]
    fn any_crashed_overrides_everything_else() {
        let s = [
            ProjectStatus::Running,
            ProjectStatus::Starting,
            ProjectStatus::Crashed,
        ];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Error);
    }

    #[test]
    fn port_conflict_is_an_error_state() {
        let s = [ProjectStatus::Running, ProjectStatus::PortConflict];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Error);
    }

    #[test]
    fn unhealthy_counts_toward_running_not_error() {
        // Unhealthy means "process is up but failing its probe". That's
        // a degraded state, not a crash — the existing dashboard treats
        // it as a yellow attention state. We collapse it into the
        // running colour (green) at the tray level so we don't claim
        // red for an issue the user can't fix from the menu bar.
        let s = [ProjectStatus::Running, ProjectStatus::Unhealthy];
        assert_eq!(AggregateStatus::from_iter(s), AggregateStatus::Running);
    }

    #[test]
    fn signature_changes_when_status_glyph_changes() {
        use crate::registry::{Project, ProjectId, ProjectType};
        use std::collections::HashMap;
        use std::collections::BTreeMap;
        use std::path::PathBuf;

        let project = Project {
            id: ProjectId::new("p1"),
            name: "demo".into(),
            path: PathBuf::from("/tmp/demo"),
            kind: ProjectType::Node,
            start_command: None,
            port: None,
            extra_ports: vec![],
            hostname: "demo.test".into(),
            https: false,
            services: vec![],
            env: BTreeMap::new(),
            readiness: None,
            auto_start: false,
            tags: vec![],
            document_root: None,
            php_version: None,
        };
        let mut s1 = HashMap::new();
        s1.insert("p1".into(), ProjectStatus::Stopped);
        let mut s2 = HashMap::new();
        s2.insert("p1".into(), ProjectStatus::Running);

        let sig1 = build_signature(std::slice::from_ref(&project), &s1);
        let sig2 = build_signature(std::slice::from_ref(&project), &s2);
        assert_ne!(sig1, sig2);
    }
}
